import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-4.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import TransitionEffect from '@/components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head className="">
        <title>Ashish Verma | Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* Page transition effect */}
      <TransitionEffect />
      <main className='flex items-center h-fit  text-white w-full dark:text-light'>
        {/* <Layout className='pt-0 md:pt-16 sm:pt-8 bg-[#554940] bg-dark'> */}
        <Layout className=' bg-dark flex align-middle items-center justify-center '>
          <div className='flex align-middle items-center justify-center w-full lg:flex-col md:flex-col gap-16 md:gap-0'>

            <div className='w-1/2 md:w-full' >
              <Image src={profilePic} alt="Ashish" className="w-full h-auto  md:inline-block md:w-full" priority sizes='(max-width: 768px) 100vw, (max-width:1200px) 50vw,50vw' />
            </div>

            <div className='w-1/2  flex flex-col items-center self-center lg:w-full lg:text-center text-white'>
              {/* <AnimatedText text="I'm Ashish Verma" className='!text-5xl !text-left xl:!text-4xl lg:!text-center lg:!text-5xl md:!text-4xl sm:!text-2xl text-white' /> */}
              <h2 className='w-full mx-auto py-2  font-bold capitalize text-6xl dark:text-light overflow-hidden sm:py-0 !text-left xl:!text-4xl lg:!text-center lg:!text-5xl md:!text-4xl sm:!text-2xl text-white'>
                I'm <span className=" tracking-[-1px] bg-gradient-to-r from-[#4c73ff] to-[#389bff] bg-clip-text text-transparent">Ashish Verma</span>
              </h2>

              <p className='my-4 text-base font-medium md:text-sm sm:text-xs font-[#D0DFFF]'>
                As a seasoned architect and interior designer with 7 years of experience, I specialize in crafting unique spaces that blend functionality and aesthetics. With a strong command of 3D design and immersive video walkthroughs, I bring ideas to life, creating environments that inspire and captivate. Explore my portfolio to see my latest projects and innovations in architectural design.
              </p>

              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/keshavCV.pdf" target="_blank" className='w-fit flex items-center !bg-[#2979FF] !text-dark p-2.5 px-6 rounded-lg text-md font-semibold hover:!bg-dark hover:!text-[#2979FF] border-2 border-solid border-transparent hover:!border-[#2979FF] dark:bg-dark dark:text-light hover:dark:bg-light hover:dark:text-dark hover:dark:border-dark md:p-2 md:px-4 md:text-base' download={true}>
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link href="mailto:int.designerav@gmail.com" target="_blank" className='ml-4 bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold capitalize  underline dark:text-light hover:bg-light hover:text-dark dark:hover:bg-dark dark:hover:text-light'>
                  Contact
                </Link>
              </div>

            </div>
          </div>
        </Layout>
        {/* Hire Me section */}
        {/* <HireMe /> */}
      </main>
    </>
  )
}
